// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: service.proto
#ifndef GRPC_service_2eproto__INCLUDED
#define GRPC_service_2eproto__INCLUDED

#include "service.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace example {

class Greeter final {
 public:
  static constexpr char const* service_full_name() {
    return "example.Greeter";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SayNumbers(::grpc::ClientContext* context, const ::example::Request& request, ::example::Reply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::example::Reply>> AsyncSayNumbers(::grpc::ClientContext* context, const ::example::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::example::Reply>>(AsyncSayNumbersRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::example::Reply>> PrepareAsyncSayNumbers(::grpc::ClientContext* context, const ::example::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::example::Reply>>(PrepareAsyncSayNumbersRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void SayNumbers(::grpc::ClientContext* context, const ::example::Request* request, ::example::Reply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SayNumbers(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::example::Reply* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void SayNumbers(::grpc::ClientContext* context, const ::example::Request* request, ::example::Reply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void SayNumbers(::grpc::ClientContext* context, const ::example::Request* request, ::example::Reply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void SayNumbers(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::example::Reply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void SayNumbers(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::example::Reply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::example::Reply>* AsyncSayNumbersRaw(::grpc::ClientContext* context, const ::example::Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::example::Reply>* PrepareAsyncSayNumbersRaw(::grpc::ClientContext* context, const ::example::Request& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status SayNumbers(::grpc::ClientContext* context, const ::example::Request& request, ::example::Reply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::example::Reply>> AsyncSayNumbers(::grpc::ClientContext* context, const ::example::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::example::Reply>>(AsyncSayNumbersRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::example::Reply>> PrepareAsyncSayNumbers(::grpc::ClientContext* context, const ::example::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::example::Reply>>(PrepareAsyncSayNumbersRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void SayNumbers(::grpc::ClientContext* context, const ::example::Request* request, ::example::Reply* response, std::function<void(::grpc::Status)>) override;
      void SayNumbers(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::example::Reply* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void SayNumbers(::grpc::ClientContext* context, const ::example::Request* request, ::example::Reply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void SayNumbers(::grpc::ClientContext* context, const ::example::Request* request, ::example::Reply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void SayNumbers(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::example::Reply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void SayNumbers(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::example::Reply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::example::Reply>* AsyncSayNumbersRaw(::grpc::ClientContext* context, const ::example::Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::example::Reply>* PrepareAsyncSayNumbersRaw(::grpc::ClientContext* context, const ::example::Request& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SayNumbers_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SayNumbers(::grpc::ServerContext* context, const ::example::Request* request, ::example::Reply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SayNumbers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SayNumbers() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SayNumbers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayNumbers(::grpc::ServerContext* /*context*/, const ::example::Request* /*request*/, ::example::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSayNumbers(::grpc::ServerContext* context, ::example::Request* request, ::grpc::ServerAsyncResponseWriter< ::example::Reply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SayNumbers<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_SayNumbers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_SayNumbers() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::example::Request, ::example::Reply>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::example::Request* request, ::example::Reply* response) { return this->SayNumbers(context, request, response); }));}
    void SetMessageAllocatorFor_SayNumbers(
        ::grpc::experimental::MessageAllocator< ::example::Request, ::example::Reply>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::example::Request, ::example::Reply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_SayNumbers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayNumbers(::grpc::ServerContext* /*context*/, const ::example::Request* /*request*/, ::example::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* SayNumbers(
      ::grpc::CallbackServerContext* /*context*/, const ::example::Request* /*request*/, ::example::Reply* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* SayNumbers(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::example::Request* /*request*/, ::example::Reply* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_SayNumbers<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_SayNumbers<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SayNumbers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SayNumbers() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SayNumbers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayNumbers(::grpc::ServerContext* /*context*/, const ::example::Request* /*request*/, ::example::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SayNumbers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SayNumbers() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SayNumbers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayNumbers(::grpc::ServerContext* /*context*/, const ::example::Request* /*request*/, ::example::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSayNumbers(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_SayNumbers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_SayNumbers() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SayNumbers(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_SayNumbers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayNumbers(::grpc::ServerContext* /*context*/, const ::example::Request* /*request*/, ::example::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* SayNumbers(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* SayNumbers(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SayNumbers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SayNumbers() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::example::Request, ::example::Reply>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::example::Request, ::example::Reply>* streamer) {
                       return this->StreamedSayNumbers(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SayNumbers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SayNumbers(::grpc::ServerContext* /*context*/, const ::example::Request* /*request*/, ::example::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSayNumbers(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::example::Request,::example::Reply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SayNumbers<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SayNumbers<Service > StreamedService;
};

}  // namespace example


#endif  // GRPC_service_2eproto__INCLUDED
