// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: service.proto

#include "service.pb.h"
#include "service.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace example {

static const char* Greeter_method_names[] = {
  "/example.Greeter/SayNumbers",
};

std::unique_ptr< Greeter::Stub> Greeter::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Greeter::Stub> stub(new Greeter::Stub(channel));
  return stub;
}

Greeter::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_SayNumbers_(Greeter_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Greeter::Stub::SayNumbers(::grpc::ClientContext* context, const ::example::Request& request, ::example::Reply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SayNumbers_, context, request, response);
}

void Greeter::Stub::experimental_async::SayNumbers(::grpc::ClientContext* context, const ::example::Request* request, ::example::Reply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SayNumbers_, context, request, response, std::move(f));
}

void Greeter::Stub::experimental_async::SayNumbers(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::example::Reply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SayNumbers_, context, request, response, std::move(f));
}

void Greeter::Stub::experimental_async::SayNumbers(::grpc::ClientContext* context, const ::example::Request* request, ::example::Reply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SayNumbers_, context, request, response, reactor);
}

void Greeter::Stub::experimental_async::SayNumbers(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::example::Reply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SayNumbers_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::example::Reply>* Greeter::Stub::AsyncSayNumbersRaw(::grpc::ClientContext* context, const ::example::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::example::Reply>::Create(channel_.get(), cq, rpcmethod_SayNumbers_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::example::Reply>* Greeter::Stub::PrepareAsyncSayNumbersRaw(::grpc::ClientContext* context, const ::example::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::example::Reply>::Create(channel_.get(), cq, rpcmethod_SayNumbers_, context, request, false);
}

Greeter::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Greeter_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Greeter::Service, ::example::Request, ::example::Reply>(
          [](Greeter::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::example::Request* req,
             ::example::Reply* resp) {
               return service->SayNumbers(ctx, req, resp);
             }, this)));
}

Greeter::Service::~Service() {
}

::grpc::Status Greeter::Service::SayNumbers(::grpc::ServerContext* context, const ::example::Request* request, ::example::Reply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace example

